# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
notifications:
  slack: 'loungeolizards:ZLbdpBYlGv10ef8qZYX7rnnJ'
osx_image: xcode61
rvm:
- 2.1.2
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
