language: C#
notifications:
  slack: loungeolizards:ZLbdpBYlGv10ef8qZYX7rnnJ
os: osx
osx_image: xcode61
rvm:
- 2.4.0
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: Gmc+NiQfnc17YKAffjDe9XXJZp86pDa64d7yLm8yJYobduBtG3vqUd7WV0m0cRkC7dqRmyozhinxb3Z0sJftL6PCXI+Bjw4C8qa42zTEHGxbzSeYJ1sg67XDCz70cwgTDY3aIJioeUnjP4zQNmWYFAbU5cHRitVzCBuZA0008Pipp2OrHOcSQBRAoWWpMGvFZqvbcUkVTvQxDOMKJPIeNEbDlA6Z3wI6b7wiIzE5Pp7gltnlXc0WCpJoz3vQgvOayUrRNChJdmeL+qjmwXaX/+dx41bd5GOC7B1y4SdSHtE2FvB52KPexLUuTGKQF3r3fLlFzqmFZXG3WxSD5E1bjm9539c3Cg3eVaCK4TK2aHz7guYL16T9EoaU71mF4qJl1rgtYemkv4fS85cLDPVtv/GTa8HzyMdOZltj9JD8Y6ALbGw6CgfTSZ5052x8MVSwWMtTdvSHJCTJuwLs1TlDOPpE4Y3pDrALelrUV98wEnbCHSw/NtlQZlen4P8OK4O3vG96MFf4kGarQiYWzw0pCvd5F9gU3Xf2Fy2ryORvoV9D5zFQxU4WhOwCE94ynbUj8VVXdTSV5kwu1nCOXiFEaLvN6qKD6aPVT5UcbZw/2a/CZp7yzaOIdYHhAtcoxFsEIzeQdzhEmoVOYF9xoHcp6v+f79QEYTplI87TXOOboyI=
  file: ./Build/android/disparity.apk
  on:
    repo: Briggybros/disparity
    tags: true